sudo: required
language: go

go:
  - 1.10.x

script:
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  
install:
  - dep ensure

after_success:
- bash <(curl -s https://codecov.io/bash)
