sudo: required
language: go

go:
  - 1.9.x

script:
  - ./ci/test.sh

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  
install:
  - dep ensure

after_success:
- bash <(curl -s https://codecov.io/bash)
