sudo: required
language: go

go:
  - 1.9.x

script:
  - go test -cover $(go list ./... | grep -v /vendor/) -coverprofile=coverage.txt -covermode=atomic

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  
install:
  - dep ensure

after_success:
- bash <(curl -s https://codecov.io/bash)
